# GHC 9.8.4
# Update `defaultGHCVersion` in `./flake.nix` when updating to resolver with different GHC version.
resolver: lts-24.9

packages:
- .

extra-deps:
- levenshtein-0.2.1.0

nix:
  packages: [zlib]


system-ghc: true
